{
 "title": "GOV.UK Chat Technical",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Application rate limits by API user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  max by (signon_user) (govuk_chat_rate_limit_api_user_read_percentage_used), \n  \"uid_and_request_type\", \"$1 - read\", \"signon_user\", \"(.*)\"\n)",
     "legendFormat": "{{uid_and_request_type}}"
    },
    {
     "expr": "label_replace(\n  max by (signon_user) (govuk_chat_rate_limit_api_user_write_percentage_used), \n  \"uid_and_request_type\", \"$1 - write\", \"signon_user\", \"(.*)\"\n)",
     "legendFormat": "{{uid_and_request_type}}"
    }
   ]
  },
  {
   "title": "Tokens used percentage - all models",
   "type": "timeseries",
   "description": "Calculation of percentage based on token limit of each model",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "itc_titan_eu_west_1 / 12000",
     "label": "Titan - eu-west-1",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    },
    {
     "expression": "itc_titan_eu_west_2 / 12000",
     "label": "Titan - eu-west-2",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    },
    {
     "expression": "(itc_gpt_oss + otc_gpt_oss) / 1000000",
     "label": "GPT OSS 120b",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "(itc_sonnet_4 + cwitc_sonnet_4 + (otc_sonnet_4 * 5)) / 30000",
     "label": "Sonnet 4",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "(itc_sonnet_4_5 + cwitc_sonnet_4_5 + (otc_sonnet_4_5 * 5)) / 50000",
     "label": "Sonnet 4.5",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "(itc_haiku_4_5 + cwitc_haiku_4_5 + (otc_haiku_4_5 * 5)) / 50000",
     "label": "Haiku 4.5",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Invocations - all models",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "dimensions": { "ModelId": "openai.gpt-oss-120b-1:0" },
     "label": "GPT OSS 120b",
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "amazon.titan-embed-text-v2:0" },
     "label": "Titan - eu-west-1",
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "amazon.titan-embed-text-v2:0" },
     "label": "Titan - eu-west-2",
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-haiku-4-5-20251001-v1:0"
     },
     "label": "Haiku 4.5",
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-20250514-v1:0"
     },
     "label": "Sonnet 4",
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-5-20250929-v1:0"
     },
     "label": "Sonnet 4.5",
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bedrock Titan Tokens Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ModelId": "amazon.titan-embed-text-v2:0" },
     "label": "eu-west-1",
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "amazon.titan-embed-text-v2:0" },
     "label": "eu-west-2",
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bedrock gpt-oss-120b Tokens Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ModelId": "openai.gpt-oss-120b-1:0" },
     "id": "itc",
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ModelId": "openai.gpt-oss-120b-1:0" },
     "id": "otc",
     "metricName": "OutputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "expression": "itc + otc",
     "label": "TotalTokenCount",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bedrock Sonnet 4 Tokens Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-20250514-v1:0"
     },
     "id": "itc",
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-20250514-v1:0"
     },
     "id": "cwitc",
     "metricName": "CacheWriteInputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-20250514-v1:0"
     },
     "id": "otc",
     "metricName": "OutputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "expression": "itc + cwitc + (otc * 5)",
     "label": "TotalTokenCount",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bedrock Sonnet 4.5 Tokens Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-5-20250929-v1:0"
     },
     "id": "itc",
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-5-20250929-v1:0"
     },
     "id": "cwitc",
     "metricName": "CacheWriteInputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-sonnet-4-5-20250929-v1:0"
     },
     "id": "otc",
     "metricName": "OutputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "expression": "itc + cwitc + (otc * 5)",
     "label": "TotalTokenCount",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bedrock Haiku 4.5 Tokens Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-haiku-4-5-20251001-v1:0"
     },
     "id": "itc",
     "metricName": "InputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-haiku-4-5-20251001-v1:0"
     },
     "id": "cwitc",
     "metricName": "CacheWriteInputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ModelId": "eu.anthropic.claude-haiku-4-5-20251001-v1:0"
     },
     "id": "otc",
     "metricName": "OutputTokenCount",
     "namespace": "AWS/Bedrock",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "expression": "itc + cwitc + (otc * 5)",
     "label": "TotalTokenCount",
     "metricEditorMode": 1,
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bedrock Service Exceptions",
   "type": "timeseries",
   "description": "This tends to happen when there are issues with the Bedrock Service and throttling is taking place",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\nfilter errorCode like /Exception/ |\nstats count(*) as error by bin(1h), errorCode",
     "logGroups": [
      {
       "accountId": "172025368201",
       "arn": "arn:aws:logs:eu-west-1:172025368201:log-group:/aws/bedrock:*",
       "name": "/aws/bedrock"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(1h)",
      "errorCode"
     ]
    }
   ]
  },
  {
   "title": "Hours Since Last Document Ingested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "(time() - (max(govuk_chat_message_queue_last_content_indexed_timestamp_seconds))) / 3600",
     "legendFormat": "HoursPassed"
    }
   ]
  },
  {
   "title": "FE HTTP Total Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "FE HTTP Requests Per Second Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "FE HTTP 5xx Error Rate Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"5..\"}[$__rate_interval])) / (sum(rate(http_requests_total{job=\"govuk-chat\"}[$__rate_interval])) / 100)",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "FE HTTP Request Duration (P75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.75, sum(rate(http_request_duration_seconds_sum{job=\"govuk-chat\"}[$__rate_interval])) / sum(rate(http_request_duration_seconds_count{job=\"govuk-chat\"}[$__rate_interval])))",
     "legendFormat": "requests/ps"
    }
   ]
  },
  {
   "title": "FE Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by(container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"apps\", pod=~\"govuk-chat-.{8,10}-.{5}\", container=~\"app|nginx\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Worker Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum by(container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"apps\", pod=~\"govuk-chat-worker-.{8,10}-.{5}\", container=~\"published-documents-consumer|worker\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "FE Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"apps\", pod=~\"govuk-chat-.{8,10}-.{5}\", container=~\"app|nginx\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Worker Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"apps\", pod=~\"govuk-chat-worker-.{8,10}-.{5}\", container=~\"published-documents-consumer|worker\"}) by(container)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "FE Pod Count",
   "type": "timeseries",
   "description": "A count of the number of FE pods in the \"Running\" state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "count(group by(pod) (kube_pod_status_phase{phase=\"Running\", pod!~\"govuk-chat-dbmigrate-.{5}\", pod=~\"govuk-chat-.{8,10}-.{5}\"}))",
     "legendFormat": "PodsRunning"
    }
   ]
  },
  {
   "title": "Worker Pod Count",
   "type": "timeseries",
   "description": "A count of the number of Worker pods in the \"Running\" state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "count(group by(pod) (kube_pod_status_phase{phase=\"Running\", pod=~\"govuk-chat-worker-.{8,10}-.{5}\"}))",
     "legendFormat": "PodsRunning"
    }
   ]
  },
  {
   "title": "Opensearch Cluster Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Opensearch Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Opensearch HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "2xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Read/Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Read/Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "chat-GOVUKENVIRONMENT-postgres" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Memory Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 112 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Network Bytes In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Bytes Used For Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(job, queue) (sidekiq_queue_backlog{job=~\"govuk-chat-worker\"})",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq Work Rate By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, queue) (rate(sidekiq_jobs_total{job=~\"govuk-chat-worker\"}[5m]))",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq Age Of Oldest Job In Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "max by(job, queue) (sidekiq_queue_latency_seconds{job=~\"govuk-chat-worker\"})",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  }
 ]
}